# Generated by Django 5.1.4 on 2024-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
                ('cotacao', models.FloatField()),
                ('pl', models.FloatField()),
                ('pvp', models.FloatField()),
                ('psr', models.FloatField()),
                ('div_yield', models.FloatField()),
                ('pativo', models.FloatField()),
                ('pcap_giro', models.FloatField()),
                ('pebit', models.FloatField()),
                ('pativ_circ_liq', models.FloatField()),
                ('ev_ebit', models.FloatField()),
                ('ev_ebitda', models.FloatField()),
                ('mrg_ebit', models.FloatField()),
                ('mrg_liq', models.FloatField()),
                ('liq_corr', models.FloatField()),
                ('roic', models.FloatField()),
                ('roe', models.FloatField()),
                ('liq_2_meses', models.FloatField()),
                ('patrim_liq', models.FloatField()),
                ('div_brut_patrim', models.FloatField()),
                ('cresc_rec_5a', models.FloatField()),
                ('plpvpa', models.FloatField()),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
    ]
