name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Dispara a pipeline ao fazer push na branch `main`
  workflow_dispatch:  # Permite disparar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: historico

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/historico:latest .

      # 4. Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/historico:latest